plugins {
	id 'net.neoforged.moddev.legacyforge' version '2.0.77'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name + "-forge"
}

repositories {

}

legacyForge {
	version = "${minecraft_version}-${loader_version}"

	validateAccessTransformers = true

	def at = file('src/main/resources/META-INF/accesstransformer.cfg')
	if (at.exists()) {
		accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
	}

	parchment {
		minecraftVersion = minecraft_version
		mappingsVersion = parchment_version
	}

	runs {
		client {
			client()
		}
	}

	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	compileOnly 'org.jetbrains:annotations:24.0.0'
}

processResources {
	def replaceProperties = new HashMap<String, String>()

	project.properties.each {key, value ->
		if (value instanceof String) {
			replaceProperties.put(key, (String) value)
		}
		return
	}

	inputs.properties replaceProperties

	filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
	withJavadocJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}