# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Loader Properties
minecraft_version=26.1
loader_version=26.1.0.1-beta
loader_version_range=[1,)
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=hot_reload_resource_packs
mod_name=Hot-Reload Resource Packs
mod_version=1.2.0
mod_description=Reloads resource packs when changes to the resourcepacks folder are made.
mod_author_original=carterisonline <me@carteris.online>
mod_author=Alfakynz
mod_license=CC0-1.0
mod_website=https://github.com/Alfakynz/hot-reload-resource-packs
maven_group=online.carteris.hot_reload_resource_packs
archives_base_name=hot_reload_resource_packs
